# 4. Create 에러 처리하기

- 에러를 생성하기 위해 **Postman을 활용**합니다.
  - Postman: API 테스트 프로그램
  - https://www.postman.com/



### 단위테스트에서 async / await 적용하기

- 단위 테스트 수정

```js
 it("should call ProductModel.create", async () => {
    // createProduct() 함수가 실행 될 때
    await productController.createProduct(req, res, next);
    // 내부에서 productModel.create 메소드가 실행 되는지
    // 여기서 단위테스트 이기 때문에 실제 Model에 영향을 받으면 안되기 떄문에 Mock 함수 사용
    // toBeCalledWith 함수를 통해 어떤 인자를 받았는지도 함께 검증
    expect(productModel.create).toBeCalledWith(newProduct);
  });

  it("should return 201 response code", async () => {
    await productController.createProduct(req, res, next);
    expect(res.statusCode).toBe(201);
    // res.send() Test
    expect(res._isEndCalled()).toBeTruthy();
  });

  it("should return josn body in response", async () => {
    // mock 함수에 리턴값을 req.body 값으로 설정
    productModel.create.mockReturnValue(newProduct);
    await productController.createProduct(req, res, next);
    expect(res._getJSONData()).toStrictEqual(newProduct);
  });
```

- controllers/products.js 수정

```js
const productModel = require("../models/product");

const createProduct = async (req, res, next) => {
  const createdProduct = await productModel.create(req.body);

  res.status(201).json(createdProduct);
};

module.exports = { createProduct };
```





### 에러 처리를 위한 단위 테스트 작성

- 에러 발생시키는 방법
  - Model에서 정의한 필수 프로퍼티를 받지 못했을 때 서버에서 에러 발생
    - Model에서 특정 프로퍼티에 `required: true`로 설정한 경우 해당 프로퍼티를 포함해서 디비에 저장해야 합니다.
    - 만약 포함하지 않는다면 **몽구스가 에러를 발생**시킵니다.

- 몽고 디비에서 처리하는 부분은 문제가 없다는 것을 가정하고 단위 테스트를 진행하기 때문에 **몽고 디비에서 발생시키는 에러 부분은 Mock 함수를 통해 처리**합니다.
- 단위 테스트 작성
  - 앞서 생성한 `next=null`값을 `jest.fn()`을 통해 mock 함수로 만들어 줍니다.

```js
let req, res, next;
beforeEach(() => {
  req = httpMocks.createRequest();
  res = httpMocks.createResponse();
  // mock 함수 생성 => 의존성을 위해 실제 next함수를 사용하지 않아야 하기 때문에
  next = jest.fn();
});

it("should handle errors", async () => {
    // description 프로퍼티가 없을 때 발생하는 에러 메시지 정의
    const errorMessage = { message: "description property missing" };
    // 비동기 처리에서 에러 프로미스 정의
    const rejectedPromise = Promise.reject(errorMessage);
    // mock 함수의 리턴 값을 정의 => rejectedPromise 반환
    productModel.create.mockReturnValue(rejectedPromise);

    // product create 함수 호출
    await productController.createProduct(req, res, next);

    // 테스트: productController.createProduct() 함수에서 에러가 발생해서  next() 함수를 호출
    // next 함수를 호출할 때 errorMessage가 넘어가는지 확인하는 테스트
    expect(next).toBeCalledWith(errorMessage);
  });
```





- Express에서 동기 요청에 관해 에러처리는 알아서 처리 / 하지만 비동기 처리에 대한 것은 서버가 망가질 수 있다.
- 그래서 next() 함수를 통해 비동기 에러를 다른 에러 핸들러로 넘겨줍니다.